# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.Web.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  displayName: 'Checkout Code'
  persistCredentials: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './DnDGen.Web/DnDGen.Web.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Server-side Unit Tests
  inputs:
    command: test
    projects: './DnDGen.Web.Tests.Unit/DnDGen.Web.Tests.Unit.csproj'
    arguments: '-v normal'
- task: DotNetCoreCLI@2
  displayName: Integration Tests
  inputs:
    command: test
    projects: './DnDGen.Web.Tests.Integration/DnDGen.Web.Tests.Integration.csproj'
    arguments: '-v normal'
- task: VSTest@2
  displayName: Client-side Unit Tests
  inputs:
    # testAssemblyVer2: './DnDGen.Web.Tests.Unit/**/chutzpah.json'
    # searchFolder: './DnDGen.Web.Tests.Unit/Scripts'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testAssemblyVer2: './DnDGen.Web.Tests.Unit/Scripts/app/*.tests.js'
    pathtoCustomTestAdapters: './DnDGen.Web.Tests.Unit/packages/Chutzpah.*/tools/'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish Artifacts
  inputs:
    pathtoPublish: './DnDGen.Web' 
    artifactName: 'dndgen-web'