pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.Apis.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
# The RollGen API
- job: RollGen_Api
  displayName: RollGen API
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  # # This avoids the issue noted here: https://github.com/NuGet/Home/issues/13729
  # # Without this step, the sdk is often 8.0.400, which has the bug
  # - task: UseDotNet@2
  #   displayName: 'HACK - Use .NET Core sdk 8.0.402'
  #   inputs:
  #     packageType: sdk
  #     version: 8.0.402
  #     installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'DnDGen.Api.RollGen/DnDGen.Api.RollGen.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.RollGen.Tests.Unit/DnDGen.Api.RollGen.Tests.Unit.csproj'
      arguments: '-v normal --collect "Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: Run Integration Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.RollGen.Tests.Integration/DnDGen.Api.RollGen.Tests.Integration.csproj'
      arguments: '-v normal --collect "Code Coverage"'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish API
    inputs:
      command: 'publish'
      projects: 'DnDGen.Api.RollGen/DnDGen.Api.RollGen.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Api/RollGen'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/Api/RollGen' 
      artifactName: 'rollgen-api'

# The TreasureGen API
- job: TreasureGen_Api
  displayName: TreasureGen API
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  # # This avoids the issue noted here: https://github.com/NuGet/Home/issues/13729
  # # Without this step, the sdk is often 8.0.400, which has the bug
  # - task: UseDotNet@2
  #   displayName: 'HACK - Use .NET Core sdk 8.0.402'
  #   inputs:
  #     packageType: sdk
  #     version: 8.0.402
  #     installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'DnDGen.Api.TreasureGen/DnDGen.Api.TreasureGen.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.TreasureGen.Tests.Unit/DnDGen.Api.TreasureGen.Tests.Unit.csproj'
      arguments: '-v normal --collect "Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: Run Integration Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.TreasureGen.Tests.Integration/DnDGen.Api.TreasureGen.Tests.Integration.csproj'
      arguments: '-v normal --collect "Code Coverage"'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish API
    inputs:
      command: 'publish'
      projects: 'DnDGen.Api.TreasureGen/DnDGen.Api.TreasureGen.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Api/TreasureGen'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/Api/TreasureGen' 
      artifactName: 'treasuregen-api'

# The CharacterGen API
- job: CharacterGen_Api
  displayName: CharacterGen API
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  # # This avoids the issue noted here: https://github.com/NuGet/Home/issues/13729
  # # Without this step, the sdk is often 8.0.400, which has the bug
  # - task: UseDotNet@2
  #   displayName: 'HACK - Use .NET Core sdk 8.0.402'
  #   inputs:
  #     packageType: sdk
  #     version: 8.0.402
  #     installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'DnDGen.Api.CharacterGen/DnDGen.Api.CharacterGen.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.CharacterGen.Tests.Unit/DnDGen.Api.CharacterGen.Tests.Unit.csproj'
      arguments: '-v normal --collect "Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: Run Integration Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.CharacterGen.Tests.Integration/DnDGen.Api.CharacterGen.Tests.Integration.csproj'
      arguments: '-v normal --collect "Code Coverage"'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish API
    inputs:
      command: 'publish'
      projects: 'DnDGen.Api.CharacterGen/DnDGen.Api.CharacterGen.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Api/CharacterGen'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/Api/CharacterGen' 
      artifactName: 'charactergen-api'

# The EncounterGen API
- job: EncounterGen_Api
  displayName: EncounterGen API
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  # # This avoids the issue noted here: https://github.com/NuGet/Home/issues/13729
  # # Without this step, the sdk is often 8.0.400, which has the bug
  # - task: UseDotNet@2
  #   displayName: 'HACK - Use .NET Core sdk 8.0.402'
  #   inputs:
  #     packageType: sdk
  #     version: 8.0.402
  #     installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'DnDGen.Api.EncounterGen/DnDGen.Api.EncounterGen.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.EncounterGen.Tests.Unit/DnDGen.Api.EncounterGen.Tests.Unit.csproj'
      arguments: '-v normal --collect "Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: Run Integration Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.EncounterGen.Tests.Integration/DnDGen.Api.EncounterGen.Tests.Integration.csproj'
      arguments: '-v normal --collect "Code Coverage"'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish API
    inputs:
      command: 'publish'
      projects: 'DnDGen.Api.EncounterGen/DnDGen.Api.EncounterGen.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Api/EncounterGen'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/Api/EncounterGen' 
      artifactName: 'encountergen-api'

# The DungeonGen API
- job: DungeonGen_Api
  displayName: DungeonGen API
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  # # This avoids the issue noted here: https://github.com/NuGet/Home/issues/13729
  # # Without this step, the sdk is often 8.0.400, which has the bug
  # - task: UseDotNet@2
  #   displayName: 'HACK - Use .NET Core sdk 8.0.402'
  #   inputs:
  #     packageType: sdk
  #     version: 8.0.402
  #     installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'DnDGen.Api.DungeonGen/DnDGen.Api.DungeonGen.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.DungeonGen.Tests.Unit/DnDGen.Api.DungeonGen.Tests.Unit.csproj'
      arguments: '-v normal --collect "Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: Run Integration Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.DungeonGen.Tests.Integration/DnDGen.Api.DungeonGen.Tests.Integration.csproj'
      arguments: '-v normal --collect "Code Coverage"'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish API
    inputs:
      command: 'publish'
      projects: 'DnDGen.Api.DungeonGen/DnDGen.Api.DungeonGen.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Api/DungeonGen'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/Api/DungeonGen' 
      artifactName: 'dungeongen-api'

# The Web API
- job: Web_Api
  displayName: Web API
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  # # This avoids the issue noted here: https://github.com/NuGet/Home/issues/13729
  # # Without this step, the sdk is often 8.0.400, which has the bug
  # - task: UseDotNet@2
  #   displayName: 'HACK - Use .NET Core sdk 8.0.402'
  #   inputs:
  #     packageType: sdk
  #     version: 8.0.402
  #     installationPath: $(Agent.ToolsDirectory)/dotnet
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      projects: 'DnDGen.Api.Web/DnDGen.Api.Web.csproj'
      arguments: '--configuration $(buildConfiguration)'
  - task: DotNetCoreCLI@2
    displayName: Run Unit Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.Web.Tests.Unit/DnDGen.Api.Web.Tests.Unit.csproj'
      arguments: '-v normal --collect "Code Coverage"'
  - task: DotNetCoreCLI@2
    displayName: Run Integration Tests
    inputs:
      command: test
      projects: 'DnDGen.Api.Web.Tests.Integration/DnDGen.Api.Web.Tests.Integration.csproj'
      arguments: '-v normal --collect "Code Coverage"'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish API
    inputs:
      command: 'publish'
      projects: 'DnDGen.Api.Web/DnDGen.Api.Web.csproj'
      publishWebProjects: false
      arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/Api/Web'
      zipAfterPublish: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Artifacts
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/Api/Web' 
      artifactName: 'dndgen-web-api'

# The DnDGen Website
- job: DnDGen_Web
  displayName: DnDGen Website
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  - task: UseNode@1
    displayName: 'Install node.js'
    inputs:
      version: '20.x'
  - task: Npm@1  
    displayName: 'Install Angular CLI'  
    inputs:  
      command: custom  
      verbose: true  
      customCommand: 'install -g @angular/cli'
  - task: Npm@1  
    displayName: 'npm install'  
    inputs:
      workingDir: '$(Build.SourcesDirectory)/dndgen-web'
      verbose: true  
      command: install
  - task: Npm@1  
    displayName: Build  
    inputs: 
      command: custom
      workingDir: '$(Build.SourcesDirectory)/dndgen-web'
      verbose: true  
      customCommand: 'run build:ci'
  - task: Npm@1  
    displayName: Run Tests
    inputs: 
      command: custom
      workingDir: '$(Build.SourcesDirectory)/dndgen-web'
      verbose: true  
      customCommand: 'run test:ci'
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: always()
    inputs:
      testResultsFiles: '**/TESTS-*.xml'
      failTaskOnFailedTests: true
  - task: PublishBuildArtifacts@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Website Artifacts
    inputs:
      ArtifactName: 'dndgen-web'
      PathtoPublish: '$(Build.SourcesDirectory)/dndgen-web/dist'
      publishLocation: 'Container'
      
# The Post-Deployment Tests
- job: deployTests
  displayName: Package Post-Deployment Tests
  steps:
  - checkout: self
    displayName: 'Checkout Code'
    persistCredentials: true
  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish Post-Deployment Test Artifacts
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/cicd/post-deployment-tests' 
      artifactName: 'dndgen-deployment-tests'
      